### ISSUE TITLE
Hacer que un colaborador se pueda registrar como instalador

### ISSUE THREAD

**Issue by reyiyo** [reyiyo/eventoL#18]
Hoy en día, si me registro como Colaborador y luego me quiero registrar como Instalador, no puedo porque ese usuario/mail ya está registrado.

Habría que ver si conviene hacer que si el usuario ya existe, lo haga instalador.

**Comment by FedeG** [comment]
In Progress

**Comment by FedeG** [comment]
Que te parece una opción mas en Collaborators que si estas logeado como colaborador te permita pasar a ser instalador.
Algo como "Switch to installer", "Become installer" o algo asi

**Comment by reyiyo** [comment]
:+1:

**Comment by FedeG** [comment]
Casi listo en el merge request #27

**Comment by FedeG** [comment]
Cambio Organizer por Collaborator

**Comment by FedeG** [comment]
Cambio Organizer por Collaborator #30
