### ISSUE TITLE
Agregar los post-processors de easy_thumbnails

### ISSUE THREAD

**Issue by reyiyo** [reyiyo/eventoL#19]
La versión actual de easy_thumbnails ahora trae optimizadores de imágenes que antes no traía. Las imágenes que suben los usuarios generalmente no están optimizadas y esto influye en la carga de la página.

Actualmente, este proceso lo corro a mano en el servidor cada vez que alguien sube una propuesta de charla, lo cual es altamente ineficiente. Estaría muy bueno poder agregarlo!

http://easy-thumbnails.readthedocs.org/en/2.1/ref/optimize/

**Comment by FedeG** [comment]
In progress

**Comment by FedeG** [comment]
Ya agregue a la wiki los paquetes a instalar en el sistema operativo

**Comment by FedeG** [comment]
Listo en merge request #25
