### ISSUE TITLE
Agregar una propuesta de charla al cronograma final

### ISSUE THREAD

**Issue by reyiyo** [reyiyo/eventoL#3]
Al momento de cerrar el cronograma final, se deben poder convertir las propuestas de charlas (TalkProposal) en charlas (Talks), asignándoles un lugar y horario. La interfaz debe ser intuitiva, fácil de usar y debe manejar conflictos de lugares y horarios.

**Comment by FedeG** [comment]
@reyiyo @AgustinCroce 

Propuesta (all inclusive):

TalkProposal
    agregarle:
        comments -> lista de Comment (modelo con comment, fecha y data del usuario para #2)
        confirmed -> Bool para saber si pasa a Talk (interfaz fácil, directamente vas armando el cronograma con las confirmed el dia de la fecha de cierre (#12) y en lugar de un formulario y todo para pasar de proposal a talk, directamente un botón "confirmar cronograma" y ahí pasar las prososal confirmed a talk. Mañana les dibujo la interfaz que me imagino así la ven)

Talk
    proposal -> TalkProposal
    room -> Room
    hour = TalkTime
    speakers = Collaborator

**Comment by reyiyo** [comment]
El tema con esto es que para cada charla, hay que manejar aula y horario. Y los horarios pueden no ser fijos (talleres de 2hs y charlas de 45', charlas que duren más que otras, etc)

**Comment by FedeG** [comment]
El TalkTime indica hora de inicio y hora de fin.

**Comment by FedeG** [comment]
Listo en #35
