### ISSUE TITLE
WYSIWYG para información del evento

### ISSUE THREAD

**Issue by reyiyo** [reyiyo/eventoL#5]
La información del evento (por sede) se muestra con un campo HTML. Habría que generar una vista con un editor WYSIWYG copado para que los colaboradores puedan editar esta información

**Comment by FedeG** [comment]
In progress

**Comment by FedeG** [comment]
te gusta: http://ckeditor.com/ ?

**Comment by FedeG** [comment]
Listo

**Comment by FedeG** [comment]
Listo en merge request:
 Footer e información de evento por sede + interfaz de WYSIWYG en el admin #27
