### ISSUE TITLE
Cronograma

### ISSUE THREAD

**Issue by FedeG** [reyiyo/eventoL#59]
Template de cronograma con las charlas confirmadas

**Comment by osiris** [comment]
Una pequeña mejora es que se puedan (des)colapsar todas charlas al mismo tiempo y si tiene un horario confirmado, mostrarlo.
http://flisol.usla.org.ar/sede/CABA/talks

**Comment by FedeG** [comment]
Podríamos agregar algo para abrir todas las charlas a la vez así uno puede ir leyendo sin problema la lista.
Después, cuando tienen un horarios confirmado lo muestra pero ya tiene que estar confirmada la charla con el horarios y aula.
Después cuando se llega a la  fecha final de propuestas ya directamente en lugar de mostrarte ese listado te muestra el cronograma del día con las aulas y las charlas que tiene confirmadas.

**Comment by reyiyo** [comment]
La funcionalidad de cronograma original, está terminada en #88.

Cierro este issue, pero creé uno nuevo para el comentario de @osiris en #89 

Gracias a todos! :D
