### ISSUE TITLE
Footer por sede

### ISSUE THREAD

**Issue by reyiyo** [reyiyo/eventoL#6]
Hoy en día en el footer se muestran imágenes que están hardcodeadas para toda la página. Habría que evaluar de dar la posibilidad a cada sede, de poner un footer (se me ocurre que con html) y hacer una vista para administrarlo

**Comment by FedeG** [comment]
Listo

**Comment by FedeG** [comment]
Listo en merge request:
 Footer e información de evento por sede + interfaz de WYSIWYG en el admin #27
