### ISSUE TITLE
Algunos mensajes (largos) en inglés no se traducen

### ISSUE THREAD

**Issue by osiris** [reyiyo/eventoL#70]
En el archivo `conf/locale/es/LC_MESSAGES/django.po` veo que los mensajes largos empienzan con msgid "".
                                                                         
    msgid "" <--- esto es el problema?                                     
    "Registration for this event is already\n"                             
     "            closed or the sede is no accepting registrations through this "
     "page. You can find more\n"                                            
     "            info"                                                     
     msgstr "La registración para este evento ya está\n"                    
     "            cerrada o la sede no está aceptando registraciones a través de esta "
     "página. Podrás encontrar más\n"                                       
     "            información" 

Hice un fork, pero no corregí e hice el pull request porque todavía no tengo una instancia de prueba para verificar.

**Comment by reyiyo** [comment]
Hola osiris! Gracias por reportar!

Es este mensaje en particular que no se te está traduciendo? El archivo ese lo autogenera django ya con ese formato y a nosotros nos está funcionando. Por ejemplo, ese mensaje lo podés ver en este momento acá: http://flisol.usla.org.ar/sede/AlmiranteBrown/registration

Si lo ves en inglés, tal vez tenga algo que ver con la caché o el idioma de tu browser (yo lo veo en castellano)

**Comment by reyiyo** [comment]
P.D. Si tenés algún problema instalando, por favor carganos un bug por acá así mejoramos la guía

**Comment by osiris** [comment]
El mensaje en inglés aparece al ir a: http://flisol.usla.org.ar/sede/Berazategui/talk/proposal/

P.D. No tuve tiempo todavía, vi que la guía era muuuy larga XD

**Comment by reyiyo** [comment]
@osiris tenés razón. El problema era que no se pueden traducir strings multiline ("""un string"""). Ahí está corregido y deployado. Si ves que falta algo, reabrí el issue.

Gracias por el reporte :D
