### ISSUE TITLE
Documentación de usuarios

### ISSUE THREAD

**Issue by reyiyo** [reyiyo/eventoL#8]
Hacer una documentación extensiva a nivel usuario y administradores, probablemente en el wiki del proyecto en github

**Comment by Gaben** [comment]
Está la parte de sedes, faltan detalles, pero está. ;)

**Comment by reyiyo** [comment]
Cierro este issue ya que la documentación básica se hizo. Abrimos issues para las documentaciones particulares de cada funcionalidad.

Gracias @Gaben !!!
