### ISSUE TITLE
View on site tira error 500

### ISSUE THREAD

**Issue by mauriciopasquier** [reyiyo/eventoL#82]
Me manda a esta url el View on site de un lugar que acabo de crear (Hacklab Oeste): http://flisol.usla.org.ar/admin/r/21/16/

No se qué funcionalidad tendrá pero bueno, reporto :P

**Comment by FedeG** [comment]
Primero, Gracias por avisar.
Segundo, encontré el porque y lo voy a documentar pero no encontré como solucionarlo (por ahora).

**Comment by FedeG** [comment]
La url http://flisol.usla.org.ar/admin/r/21/16/ es una referencia que usa django para indicar "ir la url definida en el get_absolute_url del modelo 21, objeto 16".

Que en nuestro caso es ir a la url del modelo Edificio/Building el objeto con id igual a 16.
Esto da error ya que el Edificio/Building en realidad no tiene una url definida por nosotros sino que la hereda de Place (cities.models.Place) y que tiene un a url dependiente de atributos que nosotros no usarmos y por ende da error 500.

La clase Place tiene esto:
```python 
def get_absolute_url(self):
        return "/".join([place.slug for place in self.hierarchy])
```
Y la clase que tenemos no tiene esos datos, por ende falla.

**Comment by FedeG** [comment]
Listo encontré la solución :+1: 

Gracias por reportar
