### ISSUE TITLE
Descolapsar todas las charlas

### ISSUE THREAD

**Issue by reyiyo** [reyiyo/eventoL#89]
Reportado por Osiris en #59. Pego los comentarios:

Osiris:
Una pequeña mejora es que se puedan (des)colapsar todas charlas al mismo tiempo y si tiene un horario confirmado, mostrarlo.
http://flisol.usla.org.ar/sede/CABA/talks

FedeG:

Podríamos agregar algo para abrir todas las charlas a la vez así uno puede ir leyendo sin problema la lista.
Después, cuando tienen un horarios confirmado lo muestra pero ya tiene que estar confirmada la charla con el horarios y aula.
Después cuando se llega a la fecha final de propuestas ya directamente en lugar de mostrarte ese listado te muestra el cronograma del día con las aulas y las charlas que tiene confirmadas.

**Comment by FedeG** [comment]
Listo

![mostrar](https://cloud.githubusercontent.com/assets/4097554/7223102/5b0cdbc0-e6f2-11e4-9a7b-136b9c2a5902.png)
