### ISSUE TITLE
Documentación de cómo armar el cronograma

### ISSUE THREAD

**Issue by reyiyo** [reyiyo/eventoL#90]
Documentación extensiva para el usuario que tenga que armar el cronograma de charlas, incluyendo explicación de que tiente que crear los rooms, etc.

**Comment by FedeG** [comment]
Manejo de salas -> https://github.com/reyiyo/eventoL/wiki/10_Administrar-Salas-Aulas

**Comment by FedeG** [comment]
Confirmar propuestas de charlas -> https://github.com/reyiyo/eventoL/wiki/11_Confirmar-propuestas-de-charlas

**Comment by FedeG** [comment]
Confirmar el Cronograma -> https://github.com/reyiyo/eventoL/wiki/12_Confirmar-el-cronograma
