### ISSUE TITLE
Comportamiento extraño en la lista de charlas

### ISSUE THREAD

**Issue by lobit0** [reyiyo/eventoL#97]
En http://flisol.usla.org.ar/sede/CABA/talks, si hago click en el botón verde "SHOW ALL", pareciera que puedo editar los disertantes y los horarios de comienzo y finalización de las charlas.

**Comment by FedeG** [comment]
En el día de hoy voy a repararlo.
Básicamente el botón lo único que hace es decirle a las cosas que están con collapse que se muestren y justo esos formularios lo están.

Siendo colaborador o mas esta bien que te aparezcan porque justamente podes hacer eso.
Pero como usuario sin logear están saliendo a la vista los formulario.

Seguramente en el transcurso de la mañana lo arreglo.

Gracias por el reporte !!

**Comment by FedeG** [comment]
Ya esta solucionado y va a ser subido a la pagina oficial en un rato.

**Comment by FedeG** [comment]
Listo en la pagina oficial.

Gracias por el reporte :+1:

**Comment by lobit0** [comment]
Fa, qué rápido!

No hay de qué! Gracias a vos!
